In [1]:
import pandas as pd
import numpy as np

In [2]:
movie=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movie.sample(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
4704,160000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10402, ""n...",http://www.foxsearchlight.com/once/,5723,"[{""id"": 578, ""name"": ""rock and roll""}, {""id"": ...",en,Once,A vacuum repairman moonlights as a street musi...,19.052179,"[{""name"": ""Summit Entertainment"", ""id"": 491}, ...","[{""iso_3166_1"": ""IE"", ""name"": ""Ireland""}]",2007-03-23,20710513,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,How often do you find the right person?,Once,7.3,453
4676,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,83588,"[{""id"": 378, ""name"": ""prison""}, {""id"": 187056,...",en,Middle of Nowhere,'Middle of Nowhere' follows a woman named Ruby...,2.836537,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-10-12,0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Middle of Nowhere,6.6,7
4473,750000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...",http://www.magnetreleasing.com/theinnkeepers/,58428,"[{""id"": 139, ""name"": ""anti terror""}, {""id"": 32...",en,The Innkeepers,During the final days at the Yankee Pedlar Inn...,14.386807,"[{""name"": ""Glass Eye Pix"", ""id"": 1360}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-12-01,78396,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some guests never checked out.,The Innkeepers,5.4,219

In [4]:
movie.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
credits.shape

(4803, 4)

In [7]:
movies=movie.merge(credits,on='title')

In [8]:
movies.sample(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
1514,30000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 18, ""n...",http://wwws.warnerbros.de/number23/,3594,"[{""id"": 236, ""name"": ""suicide""}, {""id"": 818, ""...",en,The Number 23,Walter Sparrow is an animal control officer th...,23.197408,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,First it takes hold of your mind...then it tak...,The Number 23,6.3,1018,3594,"[{""cast_id"": 21, ""character"": ""Walter Sparrow ...","[{""credit_id"": ""52fe439fc3a36847f8062b8d"", ""de..."
3286,0,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://www.thesecretofkells.com/,26963,"[{""id"": 14665, ""name"": ""barbarian""}, {""id"": 14...",en,The Secret of Kells,Adventure awaits 12 year old Brendan who must ...,10.621353,"[{""name"": ""G\u00e9b\u00e9ka Films"", ""id"": 4621...",...,75.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Turn the darkness into light,The Secret of Kells,7.3,181,26963,"[{""cast_id"": 1, ""character"": ""Brendan (voice)""...","[{""credit_id"": ""52fe4525c3a368484e04afe3"", ""de..."
3159,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",http://www.kites-thefilm.com/,37737,[],en,Kites,"In the harsh terrain of the Mexican desert, a ...",4.807549,"[{""name"": ""Bollywood Hollywood Production"", ""i...",...,131.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Kites,6.0,40,37737,"[{""cast_id"": 1, ""character"": ""Jay"", ""credit_id...","[{""credit_id"": ""52fe466a9251416c91053c51"", ""de..."

In [9]:
movies.shape

(4809, 23)

## EDA

# Remove unwanted columns

In [11]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [12]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.dropna(inplace=True)

In [16]:
movies.shape

(4806, 7)

In [17]:
movies.duplicated().sum()

0

## Logic Building

In [19]:
movies.iloc[0,3]                             ## genere

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
# we want the keywords like : Action,Adventure,Fantasy,Fiction
# List have multiple dictionaries
# this list is stored as string
# string to List
import ast
ast.literal_eval(movies.iloc[0,3])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [21]:
# function to get the keywords from all the dictonaries of each row
def convert(obj):
    Lt=[]
    for i in ast.literal_eval(obj):
        Lt.append(i['name'])
    return Lt

In [22]:
movies['genres']=movies['genres'].apply(convert)

In [23]:
movies.sample(3)

,movie_id,title,overview,genres,keywords,cast,crew
3682,31175,Soul Kitchen,SOUL KITCHEN film centers on a likable but hop...,"[Drama, Comedy]",[],"[{""cast_id"": 5, ""character"": ""Zinos Kazantsaki...","[{""credit_id"": ""52fe44669251416c9100f5fb"", ""de..."
2724,9603,Clueless,"Shallow, rich and socially successful Cher is ...","[Comedy, Drama, Romance]","[{""id"": 1525, ""name"": ""puberty""}, {""id"": 6270,...","[{""cast_id"": 8, ""character"": ""Cher Horowitz"", ...","[{""credit_id"": ""52fe4510c3a36847f80ba273"", ""de..."
3187,14425,PCU,Nervous high school senior Tom Lawrence visits...,[Comedy],"[{""id"": 6732, ""name"": ""mascot""}, {""id"": 171691...","[{""cast_id"": 1, ""character"": ""James 'Droz' And...","[{""credit_id"": ""596be3f99251413b20005681"", ""de..."

In [24]:
movies.iloc[0,4]                      ## Keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [25]:
movies['keywords']=movies['keywords'].apply(convert)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
movies.iloc[0,5]                  ## Cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [28]:
def convert2(obj):
    Lt=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter != 3:
            Lt.append(i['name'])
            counter+=1
        else:
            break
    return Lt

In [29]:
convert2(movies.iloc[0,5])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [30]:
movies['cast']=movies['cast'].apply(convert2)                       ## cast

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
def fetch_director(obj):
    Lt=[]
    counter=0
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            Lt.append(i['name'])
            break
    return Lt

In [33]:
movies['crew']=movies['crew'].apply(fetch_director)                  ## director

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [35]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [39]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [40]:
movies['tags'].iloc[0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [41]:
movies_new=movies[['movie_id','title','tags']]

In [42]:
movies_new

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [43]:
movies_new['tags']=movies_new['tags'].apply(lambda x:" ".join(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_1964\4235123549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(lambda x:" ".join(x))

In [44]:
movies_new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

## Text preprocessing

In [45]:
movies_new['tags']=movies_new['tags'].apply(lambda x:x.lower())

C:\Users\Admin\AppData\Local\Temp\ipykernel_1964\933172487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(lambda x:x.lower())

In [46]:
movies_new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [47]:
import nltk

In [48]:
from nltk.stem.porter import PorterStemmer

In [49]:
ps=PorterStemmer()

In [50]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [51]:
movies_new['tags']=movies_new['tags'].apply(stem)

C:\Users\Admin\AppData\Local\Temp\ipykernel_1964\3246157018.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_new['tags']=movies_new['tags'].apply(stem)

In [52]:
movies_new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vectors=cv.fit_transform(movies_new['tags']).toarray()

In [55]:
vectors.shape

(4806, 5000)

In [56]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity=cosine_similarity(vectors)

In [59]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [85]:
movies_new['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4804                                 El Mariachi
4805                                   Newlyweds
4806                   Signed, Sealed, Delivered
4807                            Shanghai Calling
4808                           My Date with Drew
Name: title, Length: 4806, dtype: object

In [91]:
movie_index=movies_new[movies_new['title']=="Pirates of the Caribbean: At World's End"].index[0]
movie_index

1

In [93]:
distances=similarity[1]
distances

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [97]:
list(enumerate(distances))

[(0, 0.08346223261119858),
 (1, 1.0),
 (2, 0.06063390625908323),
 (3, 0.03883678186903086),
 (4, 0.07504691899113898),
 (5, 0.1145873121285264),
 (6, 0.02127178149057585),
 (7, 0.1292719224987548),
 (8, 0.06262242910851494),
 (9, 0.10226199851298272),
 (10, 0.10846522890932808),
 (11, 0.07504691899113898),
 (12, 0.4140043409440133),
 (13, 0.09513029883089881),
 (14, 0.1355815361366601),
 (15, 0.1107018606925119),
 (16, 0.08346223261119858),
 (17, 0.2533201985524494),
 (18, 0.06021717344277752),
 (19, 0.1097907187727647),
 (20, 0.061357199107789626),
 (21, 0.05797710356524483),
 (22, 0.10502100630210075),
 (23, 0.09240616554505461),
 (24, 0.14097096860865022),
 (25, 0.1078676197944929),
 (26, 0.10846522890932808),
 (27, 0.08783257501821176),
 (28, 0.06160411036336974),
 (29, 0.04583492485141056),
 (30, 0.11778571185788637),
 (31, 0.10090091909944687),
 (32, 0.09007546982220897),
 (33, 0.10289915108550529),
 (34, 0.03300491809922247),
 (35, 0.10502100630210075),
 (36, 0.07845986714489121),
 (37, 0.05564148840746572),
 (38, 0.12862393885688161),
 (39, 0.05797710356524483),
 (40, 0.08134892168199606),
 (41, 0.10006255865485197),
 (42, 0.0),
 (43, 0.07204381596421111),
 (44, 0.03575992699260758),
 (45, 0.06534102628035482),
 (46, 0.11764705882352938),
 (47, 0.12478354962115543),
 (48, 0.11163607017227663),
 (49, 0.03080205518168487),
 (50, 0.08956221510397981),
 (51, 0.0425435629811517),
 (52, 0.07845986714489121),
 (53, 0.11357771260606365),
 (54, 0.03300491809922247),
 (55, 0.07440653318043244),
 (56, 0.07312724241271305),
 (57, 0.15339299776947407),
 (58, 0.09513029883089881),
 (59, 0.0958706236059213),
 (60, 0.0),
 (61, 0.140028008402801),
 (62, 0.13284223283101426),
 (63, 0.06482037235521643),
 (64, 0.03131121455425747),
 (65, 0.020646003475383347),
 (66, 0.11891287353862351),
 (67, 0.05797710356524483),
 (68, 0.09553946329477228),
 (69, 0.0700140042014005),
 (70, 0.053567158400558014),
 (71, 0.10341753799900383),
 (72, 0.11595420713048966),
 (73, 0.03500700210070025),
 (74, 0.07134772412317411),
 (75, 0.16477051091432687),
 (76, 0.050572173742417355),
 (77, 0.04565411576455765),
 (78, 0.053567158400558014),
 (79, 0.1097907187727647),
 (80, 0.03556714970147893),
 (81, 0.09709195467257715),
 (82, 0.026783579200279007),
 (83, 0.07134772412317411),
 (84, 0.08712136837380642),
 (85, 0.12065379433217113),
 (86, 0.05003127932742599),
 (87, 0.029411764705882346),
 (88, 0.09553946329477228),
 (89, 0.04565411576455765),
 (90, 0.09723055853282464),
 (91, 0.14705882352941174),
 (92, 0.06587443126365883),
 (93, 0.05003127932742599),
 (94, 0.16502459049611234),
 (95, 0.049507377148833714),
 (96, 0.08134892168199606),
 (97, 0.09799919151000504),
 (98, 0.13231403100624078),
 (99, 0.056388387443460086),
 (100, 0.03575992699260758),
 (101, 0.08134892168199606),
 (102, 0.06587443126365883),
 (103, 0.0844400661841498),
 (104, 0.14705882352941174),
 (105, 0.10969086361906957),
 (106, 0.13174886252731766),
 (107, 0.06534102628035482),
 (108, 0.05113099925649136),
 (109, 0.17149858514250882),
 (110, 0.023782574707724703),
 (111, 0.07938841860374446),
 (112, 0.05423261445466404),
 (113, 0.04583492485141056),
 (114, 0.04850712500726659),
 (115, 0.09249945801257606),
 (116, 0.05113099925649136),
 (117, 0.0939336436627724),
 (118, 0.017783574850739465),
 (119, 0.04583492485141056),
 (120, 0.0),
 (121, 0.11764705882352938),
 (122, 0.12320822072673948),
 (123, 0.047565149415449405),
 (124, 0.09513029883089881),
 (125, 0.09673824874398684),
 (126, 0.11277677488692017),
 (127, 0.11577058990186093),
 (128, 0.028583097523751468),
 (129, 0.14699878726500756),
 (130, 0.057166195047502935),
 (131, 0.08346223261119858),
 (132, 0.07134772412317411),
 (133, 0.05970814340265321),
 (134, 0.06859943405700353),
 (135, 0.0),
 (136, 0.09901475429766743),
 (137, 0.015923243882462048),
 (138, 0.16269784336399212),
 (139, 0.0850871259623034),
 (140, 0.047565149415449405),
 (141, 0.03080205518168487),
 (142, 0.08956221510397981),
 (143, 0.11458731212852641),
 (144, 0.05292561240249631),
 (145, 0.06105941257599791),
 (146, 0.017236256333167305),
 (147, 0.05882352941176469),
 (148, 0.06859943405700353),
 (149, 0.06149400462680908),
 (150, 0.09647549158488411),
 (151, 0.07151985398521515),
 (152, 0.08823529411764704),
 (153, 0.06239177481057771),
 (154, 0.03241018617760821),
 (155, 0.0),
 (156, 0.0422200330920749),
 (157, 0.0700140042014005),
 (158, 0.11778571185788639),
 (159, 0.06726727939963124),
 (160, 0.07075491376772249),
 (161, 0.03363363969981562),
 (162, 0.0700140042014005),
 (163, 0.026783579200279007),
 (164, 0.08458258116519013),
 (165, 0.024253562503633294),
 (166, 0.05292561240249631),
 (167, 0.1592324388246205),
 (168, 0.10585122480499262),
 (169, 0.11669000700233413),
 (170, 0.06755660236665673),
 (171, 0.12007302660701852),
 (172, 0.07484811885651196),
 (173, 0.04899959575500252),
 (174, 0.08238525545716345),
 (175, 0.05003127932742599),
 (176, 0.06160411036336974),
 (177, 0.0),
 (178, 0.10341753799900383),
 (179, 0.03834824944236852),
 (180, 0.023338001400466827),
 (181, 0.047565149415449405),
 (182, 0.07426106572325057),
 (183, 0.07440653318043244),
 (184, 0.053567158400558014),
 (185, 0.026783579200279007),
 (186, 0.041594516540385144),
 (187, 0.18981415059132414),
 (188, 0.023338001400466827),
 (189, 0.08084520834544433),
 (190, 0.1562904982411873),
 (191, 0.1292719224987548),
 (192, 0.05003127932742599),
 (193, 0.1332593209305539),
 (194, 0.0),
 (195, 0.06262242910851494),
 (196, 0.05492350363810897),
 (197, 0.07817631049941041),
 (198, 0.06063390625908323),
 (199, 0.27500954910846337),
 (200, 0.03834824944236852),
 (201, 0.0),
 (202, 0.03300491809922247),
 (203, 0.05882352941176469),
 (204, 0.02615328904829707),
 (205, 0.07868894753646336),
 (206, 0.09772038812426302),
 (207, 0.08134892168199606),
 (208, 0.09723055853282464),
 (209, 0.10727978097782273),
 (210, 0.05292561240249631),
 (211, 0.025854384499750957),
 (212, 0.046676002800933654),
 (213, 0.041594516540385144),
 (214, 0.0),
 (215, 0.09335200560186731),
 (216, 0.20579830217101058),
 (217, 0.06755660236665673),
 (218, 0.040422604172722164),
 (219, 0.06482037235521643),
 (220, 0.0939336436627724),
 (221, 0.05003127932742599),
 (222, 0.10555008273018725),
 (223, 0.05492350363810897),
 (224, 0.021437323142813602),
 (225, 0.049507377148833714),
 (226, 0.06369297552984819),
 (227, 0.11595420713048966),
 (228, 0.07001400420140048),
 (229, 0.0378777009539285),
 (230, 0.03883678186903086),
 (231, 0.0),
 (232, 0.11764705882352938),
 (233, 0.07312724241271305),
 (234, 0.11357771260606365),
 (235, 0.053567158400558014),
 (236, 0.030316953129541614),
 (237, 0.0700140042014005),
 (238, 0.07817631049941041),
 (239, 0.03859019663395365),
 (240, 0.09901475429766743),
 (241, 0.08346223261119858),
 (242, 0.08574929257125441),
 (243, 0.09799919151000504),
 (244, 0.03241018617760821),
 (245, 0.057166195047502935),
 (246, 0.08028956459037002),
 (247, 0.031846487764924096),
 (248, 0.04711428474315455),
 (249, 0.07312724241271305),
 (250, 0.03363363969981562),
 (251, 0.0),
 (252, 0.06431196942844081),
 (253, 0.044280744277004756),
 (254, 0.04899959575500252),
 (255, 0.026462806201248155),
 (256, 0.03934447376823168),
 (257, 0.056388387443460086),
 (258, 0.05613608914238397),
 (259, 0.06482037235521643),
 (260, 0.09240616554505461),
 (261, 0.02556549962824568),
 (262, 0.09007546982220897),
 (263, 0.10289915108550529),
 (264, 0.0),
 (265, 0.05797710356524483),
 (266, 0.05230657809659414),
 (267, 0.10289915108550529),
 (268, 0.05564148840746572),
 (269, 0.03131121455425747),
 (270, 0.09335200560186731),
 (271, 0.10006255865485197),
 (272, 0.0),
 (273, 0.0893088561378213),
 (274, 0.04067446084099803),
 (275, 0.030316953129541614),
 (276, 0.1320196723968899),
 (277, 0.03742405942825598),
 (278, 0.049507377148833714),
 (279, 0.04899959575500252),
 (280, 0.05492350363810897),
 (281, 0.04583492485141056),
 (282, 0.04711428474315455),
 (283, 0.028988551782622416),
 (284, 0.03883678186903086),
 (285, 0.06193801042615004),
 (286, 0.08258401390153339),
 (287, 0.027461751819054483),
 (288, 0.0),
 (289, 0.04850712500726659),
 (290, 0.06726727939963124),
 (291, 0.05292561240249631),
 (292, 0.0939336436627724),
 (293, 0.03131121455425747),
 (294, 0.09095085938862485),
 (295, 0.05564148840746572),
 (296, 0.06149400462680908),
 (297, 0.023338001400466827),
 (298, 0.0),
 (299, 0.06285566056425843),
 (300, 0.051708768999501914),
 (301, 0.039605901719066965),
 (302, 0.04899959575500252),
 (303, 0.029411764705882346),
 (304, 0.09737260471306503),
 (305, 0.06698164210336598),
 (306, 0.028583097523751468),
 (307, 0.08213292636386628),
 (308, 0.03575992699260758),
 (309, 0.06600983619844494),
 (310, 0.12964074471043285),
 (311, 0.026462806201248155),
 (312, 0.07938841860374446),
 (313, 0.0),
 (314, 0.0),
 (315, 0.11764705882352938),
 (316, 0.020951886854752806),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03500700210070025),
 (320, 0.03241018617760821),
 (321, 0.0),
 (322, 0.08346223261119858),
 (323, 0.03131121455425747),
 (324, 0.025854384499750957),
 (325, 0.140028008402801),
 (326, 0.029854071701326604),
 (327, 0.057166195047502935),
 (328, 0.05797710356524483),
 (329, 0.11128297681493143),
 (330, 0.10585122480499262),
 (331, 0.09513029883089881),
 (332, 0.08458258116519013),
 (333, 0.025854384499750957),
 (334, 0.10226199851298272),
 (335, 0.04899959575500252),
 (336, 0.07312724241271305),
 (337, 0.024014605321403704),
 (338, 0.0),
 (339, 0.07756315349925287),
 (340, 0.1569197342897824),
 (341, 0.05797710356524483),
 (342, 0.11363310286178552),
 (343, 0.04070627505066527),
 (344, 0.03131121455425747),
 (345, 0.04850712500726659),
 (346, 0.028988551782622416),
 (347, 0.0),
 (348, 0.06482037235521643),
 (349, 0.10713431680111603),
 (350, 0.051708768999501914),
 (351, 0.024014605321403704),
 (352, 0.05797710356524483),
 (353, 0.021780342093451605),
 (354, 0.0),
 (355, 0.05788529495093047),
 (356, 0.06369297552984819),
 (357, 0.0),
 (358, 0.06369297552984819),
 (359, 0.1320196723968899),
 (360, 0.0),
 (361, 0.10585122480499262),
 (362, 0.03363363969981562),
 (363, 0.04190377370950561),
 (364, 0.049507377148833714),
 (365, 0.0),
 (366, 0.029854071701326604),
 (367, 0.0),
 (368, 0.06859943405700353),
 (369, 0.08134892168199606),
 (370, 0.053567158400558014),
 (371, 0.050572173742417355),
 (372, 0.05003127932742599),
 (373, 0.0),
 (374, 0.08028956459037002),
 (375, 0.02160679078507214),
 (376, 0.049507377148833714),
 (377, 0.02449979787750126),
 (378, 0.03241018617760821),
 (379, 0.08939981748151894),
 (380, 0.027461751819054483),
 (381, 0.08856148855400951),
 (382, 0.0),
 (383, 0.06875238727711584),
 (384, 0.12126781251816646),
 (385, 0.030316953129541614),
 (386, 0.06937459350943204),
 (387, 0.025015639663712994),
 (388, 0.024253562503633294),
 (389, 0.12320822072673948),
 (390, 0.02782074420373286),
 (391, 0.07974522228289),
 (392, 0.09553946329477228),
 (393, 0.0),
 (394, 0.02615328904829707),
 (395, 0.0),
 (396, 0.023124864503144014),
 (397, 0.05492350363810897),
 (398, 0.046676002800933654),
 (399, 0.025015639663712994),
 (400, 0.06369297552984819),
 (401, 0.0),
 (402, 0.05492350363810897),
 (403, 0.1097907187727647),
 (404, 0.0),
 (405, 0.05882352941176469),
 (406, 0.0),
 (407, 0.06755660236665673),
 (408, 0.034299717028501764),
 (409, 0.049507377148833714),
 (410, 0.051708768999501914),
 (411, 0.08346223261119858),
 (412, 0.15171652122725207),
 (413, 0.05970814340265321),
 (414, 0.03131121455425747),
 (415, 0.018824415287446383),
 (416, 0.053567158400558014),
 (417, 0.034299717028501764),
 (418, 0.03742405942825598),
 (419, 0.07276068751089988),
 (420, 0.09513029883089881),
 (421, 0.0),
 (422, 0.03080205518168487),
 (423, 0.04356068418690321),
 (424, 0.03934447376823168),
 (425, 0.09007546982220897),
 (426, 0.056816551430892745),
 (427, 0.08346223261119858),
 (428, 0.059016710652347516),
 (429, 0.0),
 (430, 0.0),
 (431, 0.05113099925649136),
 (432, 0.04802921064280741),
 (433, 0.03300491809922247),
 (434, 0.025015639663712994),
 (435, 0.07484811885651196),
 (436, 0.02711630722733202),
 (437, 0.05423261445466404),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.024014605321403704),
 (443, 0.06755660236665673),
 (444, 0.024753688574416857),
 (445, 0.02615328904829707),
 (446, 0.02449979787750126),
 (447, 0.04543108504242546),
 (448, 0.045037734911104486),
 (449, 0.028988551782622416),
 (450, 0.022518867455552243),
 (451, 0.026462806201248155),
 (452, 0.03241018617760821),
 (453, 0.025854384499750957),
 (454, 0.049507377148833714),
 (455, 0.042874646285627205),
 (456, 0.02291746242570528),
 (457, 0.12126781251816646),
 (458, 0.04583492485141056),
 (459, 0.03656362120635653),
 (460, 0.05113099925649136),
 (461, 0.08956221510397981),
 (462, 0.034129494057038114),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.07669649888473704),
 (467, 0.06698164210336598),
 (468, 0.05882352941176469),
 (469, 0.08380754741901122),
 (470, 0.04802921064280741),
 (471, 0.09007546982220897),
 (472, 0.11277677488692017),
 (473, 0.04899959575500252),
 (474, 0.0),
 (475, 0.06937459350943204),
 (476, 0.03575992699260758),
 (477, 0.0),
 (478, 0.057166195047502935),
 (479, 0.03720326659021622),
 (480, 0.07756315349925287),
 (481, 0.025015639663712994),
 (482, 0.0),
 (483, 0.09901475429766741),
 (484, 0.06160411036336974),
 (485, 0.08346223261119858),
 (486, 0.10138954626279947),
 (487, 0.06726727939963124),
 (488, 0.05278615073083401),
 (489, 0.042874646285627205),
 (490, 0.07484811885651196),
 (491, 0.06285566056425843),
 (492, 0.08035073760083702),
 (493, 0.03241018617760821),
 (494, 0.03575992699260758),
 (495, 0.06726727939963124),
 (496, 0.017977936632415484),
 (497, 0.034299717028501764),
 (498, 0.07151985398521515),
 (499, 0.02782074420373286),
 (500, 0.027461751819054483),
 (501, 0.06482037235521643),
 (502, 0.04711428474315455),
 (503, 0.07938841860374446),
 (504, 0.03241018617760821),
 (505, 0.07151985398521515),
 (506, 0.0),
 (507, 0.06755660236665673),
 (508, 0.13391789600139503),
 (509, 0.07001400420140048),
 (510, 0.02615328904829707),
 (511, 0.09723055853282464),
 (512, 0.028988551782622416),
 (513, 0.05230657809659414),
 (514, 0.07845986714489121),
 (515, 0.05230657809659414),
 (516, 0.0),
 (517, 0.06333004963811235),
 (518, 0.04624972900628803),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.05113099925649136),
 (524, 0.03080205518168487),
 (525, 0.025015639663712994),
 (526, 0.0),
 (527, 0.0),
 (528, 0.023557142371577276),
 (529, 0.025286086871208677),
 (530, 0.08823529411764704),
 (531, 0.04899959575500252),
 (532, 0.0),
 (533, 0.031846487764924096),
 (534, 0.044280744277004756),
 (535, 0.051708768999501914),
 (536, 0.023782574707724703),
 (537, 0.07151985398521515),
 (538, 0.0),
 (539, 0.05882352941176469),
 (540, 0.05292561240249631),
 (541, 0.04465442806891065),
 (542, 0.05863223287455781),
 (543, 0.12507819831856498),
 (544, 0.08823529411764704),
 (545, 0.02615328904829707),
 (546, 0.06726727939963124),
 (547, 0.08823529411764704),
 (548, 0.0),
 (549, 0.07585826061362604),
 (550, 0.0),
 (551, 0.07974522228289),
 (552, 0.0),
 (553, 0.030316953129541614),
 (554, 0.029854071701326604),
 (555, 0.0158550498051498),
 (556, 0.028194193721730043),
 (557, 0.025854384499750957),
 (558, 0.0),
 (559, 0.031846487764924096),
 (560, 0.057166195047502935),
 (561, 0.03363363969981562),
 (562, 0.03241018617760821),
 (563, 0.05423261445466404),
 (564, 0.03131121455425747),
 (565, 0.06875238727711584),
 (566, 0.07585826061362604),
 (567, 0.0),
 (568, 0.05970814340265321),
 (569, 0.10006255865485197),
 (570, 0.03575992699260758),
 (571, 0.022327214034455325),
 (572, 0.09086217008485092),
 (573, 0.02195814375455294),
 (574, 0.024753688574416857),
 (575, 0.04802921064280741),
 (576, 0.05492350363810897),
 (577, 0.05970814340265321),
 (578, 0.039605901719066965),
 (579, 0.03080205518168487),
 (580, 0.02556549962824568),
 (581, 0.12320822072673948),
 (582, 0.04711428474315455),
 (583, 0.11961783342433499),
 (584, 0.08574929257125441),
 (585, 0.025854384499750957),
 (586, 0.047565149415449405),
 (587, 0.12507819831856498),
 (588, 0.02711630722733202),
 (589, 0.040996003084539386),
 (590, 0.031846487764924096),
 (591, 0.044280744277004756),
 (592, 0.06698164210336598),
 (593, 0.020072391147592506),
 (594, 0.05230657809659414),
 (595, 0.04850712500726659),
 (596, 0.09799919151000504),
 (597, 0.0939336436627724),
 (598, 0.0),
 (599, 0.014494275891311208),
 (600, 0.04850712500726659),
 (601, 0.05306618532579187),
 (602, 0.07204381596421111),
 (603, 0.057166195047502935),
 (604, 0.0700140042014005),
 (605, 0.0),
 (606, 0.0),
 (607, 0.10176568762666317),
 (608, 0.0),
 (609, 0.049507377148833714),
 (610, 0.07669649888473704),
 (611, 0.02449979787750126),
 (612, 0.0893088561378213),
 (613, 0.03742405942825598),
 (614, 0.051708768999501914),
 (615, 0.03241018617760821),
 (616, 0.03656362120635653),
 (617, 0.026462806201248155),
 (618, 0.09335200560186731),
 (619, 0.05423261445466404),
 (620, 0.0),
 (621, 0.034299717028501764),
 (622, 0.022327214034455325),
 (623, 0.047565149415449405),
 (624, 0.07312724241271305),
 (625, 0.0),
 (626, 0.028988551782622416),
 (627, 0.11504474832710555),
 (628, 0.051708768999501914),
 (629, 0.05113099925649136),
 (630, 0.025854384499750957),
 (631, 0.026783579200279007),
 (632, 0.0),
 (633, 0.04711428474315455),
 (634, 0.05230657809659414),
 (635, 0.023338001400466827),
 (636, 0.07426106572325057),
 (637, 0.0),
 (638, 0.0),
 (639, 0.02556549962824568),
 (640, 0.06333004963811235),
 (641, 0.0),
 (642, 0.03080205518168487),
 (643, 0.07938841860374446),
 (644, 0.05292561240249631),
 (645, 0.07001400420140048),
 (646, 0.08346223261119858),
 (647, 0.0),
 (648, 0.0),
 (649, 0.10846522890932808),
 (650, 0.05492350363810897),
 (651, 0.08035073760083702),
 (652, 0.0),
 (653, 0.03834824944236852),
 (654, 0.08783257501821176),
 (655, 0.025286086871208677),
 (656, 0.025854384499750957),
 (657, 0.07312724241271305),
 (658, 0.07669649888473704),
 (659, 0.10713431680111603),
 (660, 0.09901475429766741),
 (661, 0.08856148855400951),
 (662, 0.0),
 (663, 0.0),
 (664, 0.12738595105969638),
 (665, 0.07204381596421111),
 (666, 0.05292561240249631),
 (667, 0.0),
 (668, 0.07151985398521515),
 (669, 0.0),
 (670, 0.0),
 (671, 0.024014605321403704),
 (672, 0.029854071701326604),
 (673, 0.0),
 (674, 0.05003127932742599),
 (675, 0.047565149415449405),
 (676, 0.06063390625908323),
 (677, 0.026462806201248155),
 (678, 0.06160411036336974),
 (679, 0.0),
 (680, 0.026462806201248155),
 (681, 0.0),
 (682, 0.0),
 (683, 0.05113099925649136),
 (684, 0.0),
 (685, 0.034299717028501764),
 (686, 0.06726727939963124),
 (687, 0.05492350363810897),
 (688, 0.02291746242570528),
 (689, 0.053567158400558014),
 (690, 0.05292561240249631),
 (691, 0.0939336436627724),
 (692, 0.023124864503144014),
 (693, 0.0),
 (694, 0.11562432251572008),
 (695, 0.10502100630210075),
 (696, 0.04543108504242546),
 (697, 0.07817631049941041),
 (698, 0.04583492485141056),
 (699, 0.0),
 (700, 0.06063390625908323),
 (701, 0.0),
 (702, 0.047565149415449405),
 (703, 0.02271554252121273),
 (704, 0.024014605321403704),
 (705, 0.051708768999501914),
 (706, 0.04583492485141056),
 (707, 0.06859943405700353),
 (708, 0.02615328904829707),
 (709, 0.04356068418690321),
 (710, 0.04070627505066527),
 (711, 0.08346223261119858),
 (712, 0.02556549962824568),
 (713, 0.0),
 (714, 0.0),
 (715, 0.10502100630210075),
 (716, 0.08574929257125441),
 (717, 0.09249945801257606),
 (718, 0.023782574707724703),
 (719, 0.041594516540385144),
 (720, 0.0),
 (721, 0.034299717028501764),
 (722, 0.07276068751089988),
 (723, 0.0),
 (724, 0.07504691899113898),
 (725, 0.0),
 (726, 0.0),
 (727, 0.032555850669650596),
 (728, 0.07669649888473704),
 (729, 0.0),
 (730, 0.07996162762590017),
 (731, 0.08238525545716345),
 (732, 0.04802921064280741),
 (733, 0.06482037235521643),
 (734, 0.07067142711473183),
 (735, 0.023557142371577276),
 (736, 0.0939336436627724),
 (737, 0.05423261445466404),
 (738, 0.07312724241271305),
 (739, 0.040422604172722164),
 (740, 0.04583492485141056),
 (741, 0.05882352941176469),

In [99]:
sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

[(12, 0.4140043409440133),
 (199, 0.27500954910846337),
 (17, 0.2533201985524494),
 (216, 0.20579830217101058),
 (3572, 0.20579830217101058)]

In [60]:
def recommend(movie):
    movie_index=movies_new[movies_new['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(movies_new.iloc[i[0]].title)

In [61]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [62]:
movies_new.iloc[1216].title

'Aliens vs Predator: Requiem'

In [63]:
import pickle

In [64]:
# pickle.dump(movies_new.to_dict(),open('movies_dict.pkl','wb'))

In [65]:
movies_new['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [66]:
# pickle.dump(similarity,open('similarity.pkl','wb'))